# Generated by Django 5.0.2 on 2024-02-28 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='image',
            field=models.ImageField(blank='default.jpg', upload_to='images/'),
        ),
    ]
